### ISSUE TITLE
Can't enable toolbar with version 0.6

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#48]
0.6 only shows Deskband overlaying the left most symbol on the taskbar
and the Everything toolbar is shown as not enabled whatever I try.
No log file is generated and no user.config found at all.
All was fine with previous version

**Comment by stnkl** [comment]
> 0.6 only shows Deskband overlaying the left most symbol on the taskbar

What do you mean by that? Could you post a screenshot please?

**Comment by Horst12** [comment]
Here the screenshot
![Screenshot - 20 12 2020 , 11_14_19](https://user-images.githubusercontent.com/38587340/102710753-c1eccc00-42b4-11eb-86e5-1904b9ddfa1a.png)

**Comment by stnkl** [comment]
Ouch, that looks like that hard to debug problem as seen in #27. So weird that some of you guys have that and others don't.

**Comment by Horst12** [comment]
> 
> 
> Ouch, that looks like that hard to debug problem as seen in #27. So weird that some of you guys have that and others don't.

Looks similar but in my case there is no log file generated.
Also in all previous version the toolbar always was on the right half of the taskbar and I wasn't able to move it to the right side.
This is the first version which tries to put something on the left side
which may be part of the problem ?

**Comment by stnkl** [comment]
It actually appears like that because it opens an invisible Windows Explorer window. That's why it appears on top of the Explorer icon. I noticed I  messed up the logging in this version. That explains why the log file is empty. I am working on fixing that so we can at least pin down your issue.

In the meantime, could you maybe send me your old user.config file? If there are multiple, send them all (as long as they contain the string "EverythingToolbar" of course.

**Comment by stnkl** [comment]
Could you try this version and see if there is any log output this time?

[EverythingToolbar-0.6.0-beta2.zip](https://github.com/stnkl/EverythingToolbar/files/5720884/EverythingToolbar-0.6.0-beta2.zip)

**Comment by Horst12** [comment]
With beta3 I can enable the toolbar and it stays enabled
but the toolbar itself is not shown at all (no longer an overlay to Explorer).
On enabling I get the following exception:
==================================================
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EverythingToolbar.FilterSelector' that matches the specified binding constraints threw an exception. ---> System.TypeInitializationException: The type initializer for 'EverythingToolbar.Helpers.FilterLoader' threw an exception. ---> System.ArgumentException: The directory name C:\Users\horst\AppData\Roaming\Everything is invalid.
   at System.IO.FileSystemWatcher.set_Path(String value)
   at EverythingToolbar.Helpers.FilterLoader.CreateFileWatcher() in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\FilterLoader.cs:line 258
   at EverythingToolbar.Helpers.FilterLoader..cctor() in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\FilterLoader.cs:line 139
   --- End of inner exception stack trace ---
   at EverythingToolbar.FilterSelector..ctor() in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\FilterSelector.xaml.cs:line 12
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at EverythingToolbar.ToolbarControl..ctor() in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\ToolbarControl.xaml.cs:line 20
   at CSDeskBand.Deskband..ctor() in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Deskband.cs:line 20
==================================================================

The dir **\AppData\Roaming\Everything** is invalid because this is an portable Everything installation

**Comment by stnkl** [comment]
Perfect, That's everything I need to fix this issue. Thank you!

**Comment by stnkl** [comment]
It should work now with stable 0.6.0.

**Comment by vhanla** [comment]
Still not working.
![imagen](https://user-images.githubusercontent.com/1015823/166086399-7d319122-39dc-421c-8673-0e6601f94fe6.png)
Windows 10 x64 Pro 21H2 build 19044.1645

I myself had issues using that library to use taskbar's taskband feature, I tried other one called SharpShell, and works better... but older deskband version method (that one which shows warning on install, for example, used by NetSpeedMonitor) works even better.

BTW, Why is required to restart the entire system in order to remove the deskband? Wouldn't be better to just restart explorer process (explorer.exe and prevhost.exe)?
